[package]
name = "itex"
authors = ["oneElectron <one.electron109@protonmail.com"]
description = "Initialize a LaTex project inside a folder instantly"
readme = "README.md"
license-file = "license"
version = "1.2.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.14", features = ["blocking"], optional = true }
serde = { version = "1.0.152" }
serde_derive = { version = "1.0.152"}
serde_json = { version = "1.0.93"}
url = { version = "2.3.1", optional = true }
zip = { version = "0.6.4", optional = true }

[features]
default = ["updater"]
updater = ["dep:reqwest", "dep:url", "dep:zip"]
