[package]
name = "itex"
authors = ["oneElectron <one.electron109@protonmail.com"]
description = "Initialize a LaTex project inside a folder instantly"
readme = "README.md"
license = "GPL-3.0"
version = "1.3.5"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.*", features = ["blocking"], optional = true }
serde = { version = "1.0.*", features = ["derive"] }
serde_json = { version = "1.0.*", optional = true }
zip = { version = "0.6.*", default-features = false, features = ["deflate"], optional = true }
console = { version = "0.15.*", default-features = false, features = ["windows-console-colors", "ansi-parsing"] }
toml = "0.7.*"
clap = { version = "4.2.1", features = ["derive"] }
tokio = { version = "1.28.0", default-features = false, features = [] }

[features]
default = ["updater"]
updater = ["dep:reqwest", "dep:zip", "dep:serde_json"]

[profile.dev]
opt-level = 0
strip = false
debug = true
debug-assertions = true
overflow-checks = true
lto = false
incremental = true
rpath = false

[profile.codecov]
inherits = "test"

[profile.release]
opt-level = "z"
strip = "symbols"
debug = false
lto = true
