[package]
name = "itex"
authors = ["oneElectron <one.electron109@protonmail.com"]
description = "Initialize a LaTex project inside a folder instantly"
readme = "README.md"
license-file = "license"
version = "1.1.2"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.14", features = ["blocking"] } 
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.93"
url = "2.3.1"
zip = { version = "0.6.4" }
