[package]
name = "itex"
authors = ["oneElectron <one.electron109@protonmail.com"]
description = "Initialize a LaTex project inside a folder instantly"
readme = "README.md"
license = "GPL-3.0"
version = "1.3.3"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.*", features = ["blocking"], optional = true }
serde = { version = "1.0.*", features = ["derive"] }
serde_json = { version = "1.0.*"}
url = { version = "2.3.*", optional = true }
zip = { version = "0.6.*", optional = true }
console = "0.15.*"
toml = "0.7.*"
clap = { version = "4.2.1", features = ["derive"] }

[features]
default = ["updater"]
updater = ["dep:reqwest", "dep:url", "dep:zip"]

[profile.codecov]
inherits = "dev"