name: Ubuntu-latest

on: 
  push:
    branches:
    - main
  pull_request:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose

    - name: Run formatting checks
      run: cargo fmt --all -- --check

    - name: Run tests
      run: cargo test --verbose --no-default-features -- --test-threads=1

    - name: Run tests with updater
      run: cargo test --verbose --no-default-features --features updater -- --test-threads=1

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run formatting checks
      run: cargo fmt --all -- --check
